title: Wuyang Li's Homepage
page-top-title: Wuyang Li
top-section-bg-text: Be what you wanna be
home-subtitle: Wuyang Li&entj;|&entj;小阳先生
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
